version: '3'

services:
  nginx-rtmp:
    build: .
    container_name: nginx-rtmp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./hls:/opt/data/hls
    ports:
      - 1935:1935
      - 8080:80